name: Smart Contracts CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contracts/**'
      - 'migrations/**'
      - 'truffle-config.js'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'contracts/**'
      - 'migrations/**'
      - 'truffle-config.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install Truffle
      run: npm install -g truffle
    - name: Compile Contracts
      run: truffle compile
